# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_hi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QSlider, QListWidget, QListWidgetItem, QLineEdit, QFileDialog, QCheckBox, QAction, QActionGroup, QMainWindow, QMenu
from PyQt5.QtGui import QColor, QPixmap, QKeyEvent
from PyQt5.QtCore import Qt, QTimer
import numpy as np
import cv2
import time
import os

import f_camara_deteccion as fcd
import f_captura_video as fcv

videopath = "Archivo de video"
camara = "Camara"

#class Ui_MainWindow(object):
class Ui_MainWindow(QMainWindow):
    def setupUi(self, tonChan, camaras, colores):
        # colores = [negro, rojo, verde, azul, amarillo, fucsia, naranja, cian]
        w = 677
        h = 385
        
        self.ref_seleccionada = -1
        
        self.seleccion_camara = self.indiceCamara(camaras)
        self.selecciones_camaras = []
        
        self.seleccion_video = "/tmp/"
        
        self.estado_boton = False
        
        self.seleccion_color_obj1 = -1
        self.seleccion_color_obj2 = -1
        self.seleccion_color_calibracion = -1
        self.selecciones_colores_1 = []
        self.selecciones_colores_2 = []
        self.selecciones_colores_c = []
        
        self.iniciar_captura = None
        self.guardar_video = False
        self.dos_objetos = False

        tonChan.setObjectName("tonChan")
        tonChan.resize(w, h)
        tonChan.setFixedSize(w, h)
        self.centralwidget = QtWidgets.QWidget(tonChan)
        self.centralwidget.setObjectName("centralwidget")
        
        # Widget vista de la camara
        self.vistaCamara = QtWidgets.QLabel(self.centralwidget)
        self.vistaCamara.setGeometry(QtCore.QRect(10, 0, 461, 341))
        self.vistaCamara.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vistaCamara.setText("")
        self.vistaCamara.setObjectName("vistaCamara")
        
        self.timer = QTimer(tonChan)
        self.timer.timeout.connect(self.actualizarVistaCamara)
        
        self.iniciarCamara(self.seleccion_camara)

        # Boton iniciar
        self.botonIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.botonIniciar.setGeometry(QtCore.QRect(480, 0, 191, 91))
        self.botonIniciar.setObjectName("botonIniciar")
        
        self.botonIniciar.clicked.connect(self.cambiarBotonInicar)
        # self.botonIniciar.clicked.connect(self.printearMierda) Le puedo poner 2 funciones
        
        # Entrada de referencia y boton Aplicar
        self.entradaReferencia = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.entradaReferencia.setGeometry(QtCore.QRect(480, 140, 111, 31))
        self.entradaReferencia.setObjectName("entradaReferencia")
        self.entradaReferencia.setMaximum(999999.99)  # Establecer el máximo valor permitido
        self.entradaReferencia.setDecimals(2)
        
        self.botonAplicar = QtWidgets.QPushButton(self.centralwidget)
        self.botonAplicar.setGeometry(QtCore.QRect(600, 140, 71, 31))
        self.botonAplicar.setObjectName("botonAplicar")
        
        self.botonAplicar.clicked.connect(self.validarIngresoReferencia)
        
        # Label referencia
        self.labelReferencia = QtWidgets.QLabel(self.centralwidget)
        self.labelReferencia.setGeometry(QtCore.QRect(480, 110, 201, 21))
        self.labelReferencia.setObjectName("labelReferencia")
    
        # Check Guardar Video
        self.checkGuardarVideo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkGuardarVideo.setGeometry(QtCore.QRect(480, 180, 201, 20))
        self.checkGuardarVideo.setObjectName("checkGuardarVideo")
        
        self.checkGuardarVideo.stateChanged.connect(self.actualizarGuardarVideo)
        
        # Check Detectar Dos Objetos
        self.checkDetectarDos = QtWidgets.QCheckBox(self.centralwidget)
        self.checkDetectarDos.setGeometry(QtCore.QRect(480, 210, 201, 20))
        self.checkDetectarDos.setObjectName("checkDetectarDos")
        
        self.checkDetectarDos.stateChanged.connect(self.actualizarDosObjetos)
        
        tonChan.setCentralWidget(self.centralwidget)
        
        self.statusbar = QtWidgets.QStatusBar(tonChan)
        self.statusbar.setObjectName("statusbar")
        tonChan.setStatusBar(self.statusbar)
        
        # Menu
        self.menubar = QtWidgets.QMenuBar(tonChan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 19))
        self.menubar.setObjectName("menubar")
        
        # Menu/Archivo
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        
        # Cargar archivo de video
        self.actionCargarVideo = QtWidgets.QAction(tonChan)
        self.actionCargarVideo.setObjectName("actionCargarVideo")

        self.actionCargarVideo.triggered.connect(self.procesarArchivoVideo)
        
        # Salir
        self.actionSalir = QtWidgets.QAction(tonChan)
        self.actionSalir.setObjectName("actionSalir")
        
        self.actionSalir.triggered.connect(self.accionSalir)
        
        # Menu/Configuracion
        self.menuConfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        
        # Menu/Colores
        self.menuColor_Objeto_1 = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Objeto_1.setObjectName("menuColor_Objeto_1")
        
        self.menuColor_Objeto_2 = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Objeto_2.setObjectName("menuColor_Objeto_2")
        
        self.menuColor_Calibracion = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Calibracion.setObjectName("menuColor_Calibracion")
        for c in colores[1:]:
            c_str = str(c[2])
            color_1 = self.menuColor_Objeto_1.addAction(c_str)
            color_2 = self.menuColor_Objeto_2.addAction(c_str)
            color_1.triggered.connect(lambda _, color_1=color_1: self.seleccionColor(colores, color_1, "c1"))
            color_2.triggered.connect(lambda _, color_2=color_2: self.seleccionColor(colores, color_2, "c2"))
            color_1.setCheckable(True)
            color_2.setCheckable(True)
            self.selecciones_colores_1.append(color_1)
            self.selecciones_colores_2.append(color_2)
            
        for c in colores[:2]:
            c_str = str(c[2])
            color_c = self.menuColor_Calibracion.addAction(c_str)
            color_c.triggered.connect(lambda _, color_c=color_c: self.seleccionColor(colores, color_c, "cc"))
            color_c.setCheckable(True)
            self.selecciones_colores_c.append(color_c)
        
        self.seleccionColor(colores, self.selecciones_colores_1[3], "c1")
        self.selecciones_colores_1[3].setChecked(True)
        self.seleccionColor(colores, self.selecciones_colores_2[4], "c2")
        self.selecciones_colores_2[4].setChecked(True)
        self.seleccionColor(colores, self.selecciones_colores_c[1], "cc")
        self.selecciones_colores_c[1].setChecked(True)
        
        # Configuracion/Camaras
        self.menuCamara = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuCamara.setObjectName("menuCamara")
        
        if len(camaras) > 0:
            for c in camaras:
                c_str = str(c)
                camara = self.menuCamara.addAction(c_str)
                camara.setCheckable(True)
                camara.triggered.connect(lambda _, camara=camara: self.seleccionCamara(camara))
                self.selecciones_camaras.append(camara)
            # (self.grupoCamaras).connect(lambda _, camara=camara: self.seleccionCamara(camara))
            self.selecciones_camaras[0].setChecked(True)
        else:
                self.menuCamara.addAction("No hay camaras disponibles")
        
        # Menu/Ayuda
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        
        tonChan.setMenuBar(self.menubar)
        
        self.actionManual = QtWidgets.QAction(tonChan)
        self.actionManual.setObjectName("actionManual")
        
        self.actionAcercaDe = QtWidgets.QAction(tonChan)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        
        self.action1 = QtWidgets.QAction(tonChan)
        self.action1.setObjectName("action1") # Color_Objeto_2
        
        self.action1_2 = QtWidgets.QAction(tonChan)
        self.action1_2.setObjectName("action1_2") # Color_Objeto_1
        
        self.menuArchivo.addAction(self.actionCargarVideo)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionManual)
        self.menuAyuda.addAction(self.actionAcercaDe)
        
        self.menuConfiguracion.addAction(self.menuCamara.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Objeto_1.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Objeto_2.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Calibracion.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(tonChan)
        QtCore.QMetaObject.connectSlotsByName(tonChan)

# ------------------------------------------------------------------------------------------------
            
    def accionSalir(self):
        self.close()
        QtWidgets.QApplication.quit()

    def indiceCamara(self, lista_camaras):
        if len(lista_camaras) > 0:
            return lista_camaras[0]
        else:
            return -1
            
    def cambiarBotonInicar(self):
        if not self.estado_boton:
            if self.ref_seleccionada < 0:
                print("Referencia invalida")
            else:
                self.botonIniciar.setText("Detener")
                self.estado_boton = True
                self.comenzarGrabacion(self.guardar_video)
        else:
            self.botonIniciar.setText("Iniciar")
            self.estado_boton = False
            if self.iniciar_captura is not None:
                self.iniciar_captura.release()
                self.iniciar_captura = None
                self.procesarGrabacion()

    def validarIngresoReferencia(self):
        rfs = (self.entradaReferencia.text()).replace(',', '.') # Siempre es str
        try:
            self.ref_seleccionada = abs(float(rfs))
            print(f"Valor ingresado: {rfs} Numerico: {self.ref_seleccionada}")
        except ValueError:
            print("Error: La cadena contiene caracteres no válidos para convertir a float")

    def seleccionCamara(self, seleccion):
        camara_text = seleccion.text()
        if str(self.seleccion_camara) != camara_text:
            for c in self.selecciones_camaras:
                if c.isChecked():
                    c.setChecked(False)
        
            self.seleccion_camara = int(camara_text)
            print(f"Camara seleccionada: {self.seleccion_camara}")
            self.cambiarCamara(self.seleccion_camara)
        
        seleccion.setChecked(True)
    
    def tuplaColor(self, c1, c2):
        return (np.array(c1), np.array(c2))
    
    def seleccionColor(self, colores, seleccion, color_cambiar):
        
        def verificarSeleccion(objetivo, lista_selecciones):
            if objetivo != -1:
                for item_color in lista_selecciones:
                    if item_color.isChecked():
                        item_color.setChecked(False)
                        
        def buscarColor(nombre_color, lista_colores):
            tupla_color = 0
            # color = (color_bajo, color_alto, nombre_color_str)
            for color in lista_colores:
                if nombre_color in color:
                    # tupla_color = (color[0], color[1])
                    tupla_color = self.tuplaColor(color[0], color[1])
                    break
            return tupla_color
        
        if color_cambiar == "c1":     
            color_text = seleccion.text()
            verificarSeleccion(self.seleccion_color_obj1, self.selecciones_colores_1)
            self.seleccion_color_obj1 = buscarColor(color_text, colores)
            seleccion.setChecked(True)
            print(f"Color Objeto 1 seleccionado: {color_text}")
            
        if color_cambiar == "c2":     
            color_text = seleccion.text()
            verificarSeleccion(self.seleccion_color_obj2, self.selecciones_colores_2)
            self.seleccion_color_obj2 = buscarColor(color_text, colores)
            seleccion.setChecked(True)
            print(f"Color Objeto 2 seleccionado: {color_text}")
            
        if color_cambiar == "cc":     
            color_text = seleccion.text()
            verificarSeleccion(self.seleccion_color_calibracion, self.selecciones_colores_c)
            self.seleccion_color_calibracion = buscarColor(color_text, colores)
            seleccion.setChecked(True)
            print(f"Color Calibracion seleccionado: {color_text}")
    
    def actualizarGuardarVideo(self):
        self.guardar_video = self.checkGuardarVideo.isChecked()
        print(f"Guardar video: {self.guardar_video}")
        
    def actualizarDosObjetos(self):
        self.dos_objetos = self.checkDetectarDos.isChecked()
        print(f"Detectar 2 objetos: {self.dos_objetos}")
        
    def cargarArchivoVideo(self):
        # Hacer algo si por alguna razon no cargo nada, es decir, le doy a cancelar
        opciones = QFileDialog.Options()
        opciones |= QFileDialog.ReadOnly  # Opcional: abrir el archivo en modo solo lectura
        
        archivo, _ = QFileDialog.getOpenFileName(self, "Seleccionar Archivo", "", "Todos los Archivos (*)", options=opciones)

        return archivo
    
    def procesarArchivoVideo(self):
        if self.seleccion_color_obj1 == -1:
            print("Color no seleccionado")
        else:
            if self.ref_seleccionada == -1:
                print("Referencia no cargada")
            else:
                self.seleccion_video = self.cargarArchivoVideo()
                cap = cv2.VideoCapture(self.seleccion_video)
                fcd.iniciar_deteccion(self.seleccion_color_obj1, self.seleccion_color_obj2, self.seleccion_color_calibracion, cap, self.ref_seleccionada, False, True, "ui", self.dos_objetos)

    def procesarGrabacion(self):
        # Hacer para que borre la grabacion si no se puso guardar video
        cap = cv2.VideoCapture(self.seleccion_video)
        fcd.iniciar_deteccion(self.seleccion_color_obj1, self.seleccion_color_obj2, self.seleccion_color_calibracion, cap, self.ref_seleccionada, False, False, "ui", self.dos_objetos)
        if not self.guardar_video:
            print(f"Archivo {self.seleccion_video} borrado")
            os.remove(self.seleccion_video)

    def actualizarVistaCamara(self):
        # Modificar esta funcion para que muestre las marcas de deteccion
        tamaño_widget = self.vistaCamara.size()

        frame_original, frame_mostrar = fcv.previsualizarVideo(self.cap, tamaño_widget, self.ref_seleccionada, self.seleccion_color_obj1, self.seleccion_color_obj2, self.seleccion_color_calibracion, self.dos_objetos)

        imagen = QtGui.QImage(frame_mostrar, frame_mostrar.shape[1], frame_mostrar.shape[0], frame_mostrar.strides[0], QtGui.QImage.Format_RGB888)
        pixmap = QtGui.QPixmap.fromImage(imagen)
        self.vistaCamara.setPixmap(pixmap)
            
        if self.iniciar_captura is not None:
            frame_writer = cv2.cvtColor(frame_original, cv2.COLOR_RGB2BGR)
            self.iniciar_captura.write(frame_writer)

    def iniciarCamara(self, indice_camara):
        self.cap = cv2.VideoCapture(indice_camara)
        # self.fps = self.cap.get(cv2.CAP_PROP_FPS)
        self.fps = 10 # Funciono ???
        self.timer.start(int(1000 / self.fps))

    def cambiarCamara(self, seleccion_camara):
        print(seleccion_camara, self.seleccion_camara, self.cap.isOpened())
        if self.cap.isOpened():
            self.cap.release()
            self.iniciarCamara(seleccion_camara)
       
    def elegirDirectorioGuardarGrabacion(self):
        directorio = QFileDialog.getExistingDirectory(self, 'Seleccionar Directorio')
        print(f"Directorio: {directorio}")
        # self.entrada_directorio.setText(directorio)
        
        return directorio
            
    def comenzarGrabacion(self, guardar_video):
        fecha = time.strftime("%a, %d %b %Y %H:%M:%S", time.gmtime())
        nombre_archivo = fecha[5:7]+"-"+fecha[8:11]+"-"+fecha[12:16]+"_"+fecha[17:25]+".avi"
        if guardar_video:
             directorio = self.elegirDirectorioGuardarGrabacion()
             self.seleccion_video = directorio+"/"+nombre_archivo
        else:
             self.seleccion_video = "/tmp/"+nombre_archivo
        
        fourcc = cv2.VideoWriter_fourcc(*'XVID')
        fps = self.fps
        
        tamaño_widget = self.vistaCamara.size()
        ancho_widget = tamaño_widget.width()
        alto_widget = tamaño_widget.height()
        
        self.iniciar_captura = cv2.VideoWriter(self.seleccion_video, fourcc, fps, (ancho_widget, alto_widget))
        
# ------------------------------------------------------------------------------------------------
        
    def retranslateUi(self, tonChan):
        _translate = QtCore.QCoreApplication.translate
        tonChan.setWindowTitle(_translate("tonChan", "tonChan"))
        self.botonIniciar.setText(_translate("tonChan", "Iniciar"))
        self.labelReferencia.setText(_translate("tonChan", "Longitud lado inferior (cm)"))
        self.checkGuardarVideo.setText(_translate("tonChan", "Guardar archivo de video"))
        self.checkDetectarDos.setText(_translate("tonChan", "Detectar dos objetos"))
        self.botonAplicar.setText(_translate("tonChan", "Aplicar"))
        self.menuArchivo.setTitle(_translate("tonChan", "Archivo"))
        self.menuAyuda.setTitle(_translate("tonChan", "Ayuda"))
        self.menuConfiguracion.setTitle(_translate("tonChan", "Configuracion"))
        self.menuColor_Objeto_1.setTitle(_translate("tonChan", "Color Objeto 1"))
        self.menuColor_Objeto_2.setTitle(_translate("tonChan", "Color Objeto 2"))
        self.menuColor_Calibracion.setTitle(_translate("tonChan", "Color Calibracion"))
        self.menuCamara.setTitle(_translate("tonChan", "Camara"))
        self.actionManual.setText(_translate("tonChan", "Manual"))
        self.actionAcercaDe.setText(_translate("tonChan", "Acerca de"))
        self.actionCargarVideo.setText(_translate("tonChan", "Cargar archivo de video"))
        self.actionSalir.setText(_translate("tonChan", "Salir"))
