# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_hi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QSlider, QListWidget, QListWidgetItem, QLineEdit, QFileDialog, QCheckBox, QAction, QActionGroup, QMainWindow, QMenu
from PyQt5.QtGui import QColor, QPixmap, QKeyEvent
from PyQt5.QtCore import Qt

videopath = "Archivo de video"
camara = "Camara"

#class Ui_MainWindow(object):
class Ui_MainWindow(QMainWindow):
    def setupUi(self, tonChan, camaras, colores):
        w = 677
        h = 385
        
        self.ref_seleccionada = -1
        
        self.seleccion_cam = self.indiceCamara(camaras)
        self.selecciones_camaras = []
        
        self.estado_boton = False
        
        self.seleccion_color_obj1 = -1
        self.seleccion_color_obj2 = -1
        self.seleccion_color_calibracion = -1
        self.selecciones_colores_1 = []
        self.selecciones_colores_2 = []
        self.selecciones_colores_c = []
        
        self.guardar_video = False
        self.dos_objetos = False

        tonChan.setObjectName("tonChan")
        tonChan.resize(w, h)
        tonChan.setFixedSize(w, h)
        self.centralwidget = QtWidgets.QWidget(tonChan)
        self.centralwidget.setObjectName("centralwidget")
        
        # Widget vista de la camara
        self.vistaCamara = QtWidgets.QLabel(self.centralwidget)
        self.vistaCamara.setGeometry(QtCore.QRect(10, 0, 461, 341))
        self.vistaCamara.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vistaCamara.setText("")
        self.vistaCamara.setObjectName("vistaCamara")
        
        # Boton iniciar
        self.botonIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.botonIniciar.setGeometry(QtCore.QRect(480, 0, 191, 91))
        self.botonIniciar.setObjectName("botonIniciar")
        self.botonIniciar.clicked.connect(self.cambiarBotonInicar)
        
        # Entrada de referencia y boton Aplicar
        self.entradaReferencia = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.entradaReferencia.setGeometry(QtCore.QRect(480, 140, 111, 31))
        self.entradaReferencia.setObjectName("entradaReferencia")
        self.entradaReferencia.setMaximum(999999.99)  # Establecer el máximo valor permitido
        self.entradaReferencia.setDecimals(2)
        
        self.botonAplicar = QtWidgets.QPushButton(self.centralwidget)
        self.botonAplicar.setGeometry(QtCore.QRect(600, 140, 71, 31))
        self.botonAplicar.setObjectName("botonAplicar")
        
        self.botonAplicar.clicked.connect(self.validarIngresoReferencia)
        
        # Label referencia
        self.labelReferencia = QtWidgets.QLabel(self.centralwidget)
        self.labelReferencia.setGeometry(QtCore.QRect(480, 110, 201, 21))
        self.labelReferencia.setObjectName("labelReferencia")
    
        # Check Guardar Video
        self.checkGuardarVideo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkGuardarVideo.setGeometry(QtCore.QRect(480, 180, 201, 20))
        self.checkGuardarVideo.setObjectName("checkGuardarVideo")
        
        self.checkGuardarVideo.stateChanged.connect(self.actualizarGuardarVideo)
        
        # Check Detectar Dos Objetos
        self.checkDetectarDos = QtWidgets.QCheckBox(self.centralwidget)
        self.checkDetectarDos.setGeometry(QtCore.QRect(480, 210, 201, 20))
        self.checkDetectarDos.setObjectName("checkDetectarDos")
        
        self.checkDetectarDos.stateChanged.connect(self.actualizarDosObjetos)
        
        tonChan.setCentralWidget(self.centralwidget)
        
        self.statusbar = QtWidgets.QStatusBar(tonChan)
        self.statusbar.setObjectName("statusbar")
        tonChan.setStatusBar(self.statusbar)
        
        # Menu
        self.menubar = QtWidgets.QMenuBar(tonChan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 19))
        self.menubar.setObjectName("menubar")
        
        # Menu/Archivo
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        
        # Cargar archivo de video
        self.actionCargarVideo = QtWidgets.QAction(tonChan)
        self.actionCargarVideo.setObjectName("actionCargarVideo")

        self.actionCargarVideo.triggered.connect(self.cargarArchivoVideo)
        
        self.actionSalir = QtWidgets.QAction(tonChan)
        self.actionSalir.setObjectName("actionSalir")
        
        # Menu/Configuracion
        self.menuConfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        
        # Menu/Colores
        self.menuColor_Objeto_1 = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Objeto_1.setObjectName("menuColor_Objeto_1")
        
        self.menuColor_Objeto_2 = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Objeto_2.setObjectName("menuColor_Objeto_2")
        
        self.menuColor_Calibracion = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Calibracion.setObjectName("menuColor_Calibracion")

        for c in colores[1:]:
            c_str = str(c[2])
            color_1 = self.menuColor_Objeto_1.addAction(c_str)
            color_2 = self.menuColor_Objeto_2.addAction(c_str)
            color_1.setCheckable(True)
            color_2.setCheckable(True)
            color_1.triggered.connect(lambda _, color_1=color_1: self.seleccionColor(color_1, "c1"))
            color_2.triggered.connect(lambda _, color_2=color_2: self.seleccionColor(color_2, "c2"))
            self.selecciones_colores_1.append(color_1)
            self.selecciones_colores_2.append(color_2)
            
        for c in colores[:2]:
            # (self.menuColor_Calibracion.addAction(c[2])).setCheckable(True)
            c_str = str(c[2])
            color_c = self.menuColor_Calibracion.addAction(c_str)
            color_c.setCheckable(True)
            color_c.triggered.connect(lambda _, color_c=color_c: self.seleccionColor(color_c, "cc"))
            self.selecciones_colores_c.append(color_c)
        
        # Configuracion/Camaras
        self.menuCamara = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuCamara.setObjectName("menuCamara")
        
        if len(camaras) > 0:
            for c in camaras:
                c_str = str(c)
                camara = self.menuCamara.addAction(c_str)
                camara.setCheckable(True)
                camara.triggered.connect(lambda _, camara=camara: self.seleccionCamara(camara))
                self.selecciones_camaras.append(camara)
            # (self.grupoCamaras).connect(lambda _, camara=camara: self.seleccionCamara(camara))
        else:
                self.menuCamara.addAction("No hay camaras disponibles")
        
        # Menu/Ayuda
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        
        tonChan.setMenuBar(self.menubar)
        
        self.actionManual = QtWidgets.QAction(tonChan)
        self.actionManual.setObjectName("actionManual")
        
        self.actionAcercaDe = QtWidgets.QAction(tonChan)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        
        self.action1 = QtWidgets.QAction(tonChan)
        self.action1.setObjectName("action1") # Color_Objeto_2
        
        self.action1_2 = QtWidgets.QAction(tonChan)
        self.action1_2.setObjectName("action1_2") # Color_Objeto_1
        
        self.menuArchivo.addAction(self.actionCargarVideo)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionManual)
        self.menuAyuda.addAction(self.actionAcercaDe)
        
        self.menuConfiguracion.addAction(self.menuCamara.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Objeto_1.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Objeto_2.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Calibracion.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(tonChan)
        QtCore.QMetaObject.connectSlotsByName(tonChan)
                
    def indiceCamara(self, lista_camaras):
        if len(lista_camaras) > 0:
            return lista_camaras[0]
        else:
            return -1
            
    def cambiarBotonInicar(self):
        if not self.estado_boton:
            self.botonIniciar.setText("Detener")
            self.estado_boton = True
        else:
            self.botonIniciar.setText("Iniciar")
            self.estado_boton = False

    def validarIngresoReferencia(self):
        rfs = (self.entradaReferencia.text()).replace(',', '.') # Siempre es str
        try:
            self.ref_seleccionada = abs(float(rfs))
            print(f"Valor ingresado: {rfs} Numerico: {self.ref_seleccionada}")
        except ValueError:
            print("Error: La cadena contiene caracteres no válidos para convertir a float")

    def seleccionCamara(self, seleccion):
        camara_text = seleccion.text()
        if self.seleccion_cam != -1:
            for c in self.selecciones_camaras:
                if c.text() == self.seleccion_cam:
                    c.setChecked(False)
                    break
        
        self.seleccion_cam = camara_text
        seleccion.setChecked(True)
        print(f"Camara seleccionada: {self.seleccion_cam}")
        
    def seleccionColor(self, seleccion, color_cambiar):
        
        def verificarSeleccion(objetivo, lista_selecciones):
            if objetivo != -1:
                for c in lista_selecciones:
                    if c.text() == objetivo:
                        c.setChecked(False)
                        break
        
        if color_cambiar == "c1":     
            color_text = seleccion.text()
            verificarSeleccion(self.seleccion_color_obj1, self.selecciones_colores_1)
            self.seleccion_color_obj1 = color_text
            seleccion.setChecked(True)
            print(f"Color Objeto 1 seleccionado: {self.seleccion_color_obj1}")
            
        if color_cambiar == "c2":     
            color_text = seleccion.text()
            verificarSeleccion(self.seleccion_color_obj2, self.selecciones_colores_2)
            self.seleccion_color_obj2 = color_text
            seleccion.setChecked(True)
            print(f"Color Objeto 2 seleccionado: {self.seleccion_color_obj2}")
            
        if color_cambiar == "cc":     
            color_text = seleccion.text()
            verificarSeleccion(self.seleccion_color_calibracion, self.selecciones_colores_c)
            self.seleccion_color_calibracion = color_text
            seleccion.setChecked(True)
            print(f"Color Calibracion seleccionado: {self.seleccion_color_calibracion}")
    
    def actualizarGuardarVideo(self):
        self.guardar_video = self.checkGuardarVideo.isChecked()
        print(f"Guardar video: {self.guardar_video}")
        
    def actualizarDosObjetos(self):
        self.dos_objetos = self.checkDetectarDos.isChecked()
        print(f"Detectar 2 objetos: {self.dos_objetos}")
        
    def cargarArchivoVideo(self):
        # Hacer algo si por alguna razon no cargo nada, es decir, le doy a cancelar
        opciones = QFileDialog.Options()
        opciones |= QFileDialog.ReadOnly  # Opcional: abrir el archivo en modo solo lectura
        
        archivo, _ = QFileDialog.getOpenFileName(self, "Seleccionar Archivo", "", "Todos los Archivos (*)", options=opciones)

        """
        nombre_archivo = "juan"
        cap = cv2.VideoCapture(archivo)lf.ref_seleccionada, False, True, nombre_archivo)
        """

    def capturaVideo():
        if self.estado_boton:
            return 0
        else: return 0
    def retranslateUi(self, tonChan):
        _translate = QtCore.QCoreApplication.translate
        tonChan.setWindowTitle(_translate("tonChan", "tonChan"))
        self.botonIniciar.setText(_translate("tonChan", "Iniciar"))
        self.labelReferencia.setText(_translate("tonChan", "Longitud lado inferior (cm)"))
        self.checkGuardarVideo.setText(_translate("tonChan", "Guardar archivo de video"))
        self.checkDetectarDos.setText(_translate("tonChan", "Detectar dos objetos"))
        self.botonAplicar.setText(_translate("tonChan", "Aplicar"))
        self.menuArchivo.setTitle(_translate("tonChan", "Archivo"))
        self.menuAyuda.setTitle(_translate("tonChan", "Ayuda"))
        self.menuConfiguracion.setTitle(_translate("tonChan", "Configuracion"))
        self.menuColor_Objeto_1.setTitle(_translate("tonChan", "Color Objeto 1"))
        self.menuColor_Objeto_2.setTitle(_translate("tonChan", "Color Objeto 2"))
        self.menuColor_Calibracion.setTitle(_translate("tonChan", "Color Calibracion"))
        self.menuCamara.setTitle(_translate("tonChan", "Camara"))
        self.actionManual.setText(_translate("tonChan", "Manual"))
        self.actionAcercaDe.setText(_translate("tonChan", "Acerca de"))
        self.actionCargarVideo.setText(_translate("tonChan", "Cargar archivo de video"))
        self.actionSalir.setText(_translate("tonChan", "Salir"))
