# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_hi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QSlider, QListWidget, QListWidgetItem, QLineEdit, QFileDialog, QCheckBox, QAction, QActionGroup, QMainWindow, QMenu
from PyQt5.QtGui import QColor, QPixmap, QKeyEvent
from PyQt5.QtCore import Qt

videopath = "Archivo de video"
camara = "Camara"

class Ui_MainWindow(object):
    def setupUi(self, tonChan, camaras, colores):
        w = 677
        h = 385
        
        self.ref_seleccionada = -1
        self.seleccion_cam = -1
        self.selecciones_camaras = []

        tonChan.setObjectName("tonChan")
        tonChan.resize(w, h)
        tonChan.setFixedSize(w, h)
        self.centralwidget = QtWidgets.QWidget(tonChan)
        self.centralwidget.setObjectName("centralwidget")
        
        self.vistaCamara = QtWidgets.QLabel(self.centralwidget)
        self.vistaCamara.setGeometry(QtCore.QRect(10, 0, 461, 341))
        self.vistaCamara.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.vistaCamara.setText("")
        self.vistaCamara.setObjectName("vistaCamara")
        
        # Boton iniciar
        self.estado_boton = False
        self.botonIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.botonIniciar.setGeometry(QtCore.QRect(480, 0, 191, 91))
        self.botonIniciar.setObjectName("botonIniciar")
        self.botonIniciar.clicked.connect(self.cambiarBotonInicar)
        
        # Entrada de referencia y boton Aplicar
        self.entradaReferencia = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.entradaReferencia.setGeometry(QtCore.QRect(480, 140, 111, 31))
        self.entradaReferencia.setObjectName("entradaReferencia")
        
        self.botonAplicar = QtWidgets.QPushButton(self.centralwidget)
        self.botonAplicar.setGeometry(QtCore.QRect(600, 140, 71, 31))
        self.botonAplicar.setObjectName("botonAplicar")
        
        self.botonAplicar.clicked.connect(self.validarIngresoReferencia)
        
        # Label referencia
        self.labelReferencia = QtWidgets.QLabel(self.centralwidget)
        self.labelReferencia.setGeometry(QtCore.QRect(480, 110, 201, 21))
        self.labelReferencia.setObjectName("labelReferencia")
    
        # Check Guardar Video
        self.checkGuardarVideo = QtWidgets.QCheckBox(self.centralwidget)
        self.checkGuardarVideo.setGeometry(QtCore.QRect(480, 180, 201, 20))
        self.checkGuardarVideo.setObjectName("checkGuardarVideo")
        
        # Check Detectar Dos Objetos
        self.checkDetectarDos = QtWidgets.QCheckBox(self.centralwidget)
        self.checkDetectarDos.setGeometry(QtCore.QRect(480, 210, 201, 20))
        self.checkDetectarDos.setObjectName("checkDetectarDos")
        
        tonChan.setCentralWidget(self.centralwidget)
        
        self.statusbar = QtWidgets.QStatusBar(tonChan)
        self.statusbar.setObjectName("statusbar")
        tonChan.setStatusBar(self.statusbar)
        
        # Menu
        self.menubar = QtWidgets.QMenuBar(tonChan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 19))
        self.menubar.setObjectName("menubar")
        
        # Menu/Archivo
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        
        self.actionCargarVideo = QtWidgets.QAction(tonChan)
        self.actionCargarVideo.setObjectName("actionCargarVideo")
        
        self.actionSalir = QtWidgets.QAction(tonChan)
        self.actionSalir.setObjectName("actionSalir")
        
        # Menu/Configuracion
        self.menuConfiguracion = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracion.setObjectName("menuConfiguracion")
        
        # Menu/Colores
        self.menuColor_Objeto_1 = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Objeto_1.setObjectName("menuColor_Objeto_1")
        
        self.menuColor_Objeto_2 = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Objeto_2.setObjectName("menuColor_Objeto_2")
        
        self.menuColor_Calibracion = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuColor_Calibracion.setObjectName("menuColor_Calibracion")
        
        for c in colores[1:]:
            # item = QListWidgetItem(c[2])
            (self.menuColor_Objeto_1.addAction(c[2])).setCheckable(True)
            (self.menuColor_Objeto_2.addAction(c[2])).setCheckable(True)
        
        for c in colores[:2]:
            (self.menuColor_Calibracion.addAction(c[2])).setCheckable(True)
        
        # Configuracion/Camaras
        self.menuCamara = QtWidgets.QMenu(self.menuConfiguracion)
        self.menuCamara.setObjectName("menuCamara")
        
        if len(camaras) > 0:
            for c in camaras:
                c_str = str(c)
                camara = self.menuCamara.addAction(c_str)
                camara.setCheckable(True)
                camara.triggered.connect(lambda _, camara=camara: self.seleccionCamara(camara))
                self.selecciones_camaras.append(camara)
            # (self.grupoCamaras).connect(lambda _, camara=camara: self.seleccionCamara(camara))
        else:
                self.menuCamara.addAction("No hay camaras disponibles")
        
        # Menu/Ayuda
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        
        tonChan.setMenuBar(self.menubar)
        
        self.actionManual = QtWidgets.QAction(tonChan)
        self.actionManual.setObjectName("actionManual")
        
        self.actionAcercaDe = QtWidgets.QAction(tonChan)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        
        self.action1 = QtWidgets.QAction(tonChan)
        self.action1.setObjectName("action1") # Color_Objeto_2
        
        self.action1_2 = QtWidgets.QAction(tonChan)
        self.action1_2.setObjectName("action1_2") # Color_Objeto_1
        
        self.menuArchivo.addAction(self.actionCargarVideo)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionManual)
        self.menuAyuda.addAction(self.actionAcercaDe)
        
        self.menuConfiguracion.addAction(self.menuCamara.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Objeto_1.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Objeto_2.menuAction())
        self.menuConfiguracion.addAction(self.menuColor_Calibracion.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(tonChan)
        QtCore.QMetaObject.connectSlotsByName(tonChan)
                
    def cambiarBotonInicar(self):
        if not self.estado_boton:
            self.botonIniciar.setText("Detener")
            self.estado_boton = True
        else:
            self.botonIniciar.setText("Iniciar")
            self.estado_boton = False

    def validarIngresoReferencia(self):
        rfs = (self.entradaReferencia.text()).replace(',', '.') # Siempre es str
        try:
            self.ref_seleccionada = abs(float(rfs))
            print(f"Valor ingresado: {rfs} Numerico: {self.ref_seleccionada}")
        except ValueError:
            print("Error: La cadena contiene caracteres no válidos para convertir a float")

    def seleccionCamara(self, seleccion):
        camara_text = seleccion.text()
        if self.seleccion_cam != -1:
            for c in self.selecciones_camaras:
                if c.text() == self.seleccion_cam:
                    c.setChecked(False)
                    break
        
        self.seleccion_cam = camara_text
        seleccion.setChecked(True)
        print(f"Camara seleccionada: {camara_text}")
    
    def retranslateUi(self, tonChan):
        _translate = QtCore.QCoreApplication.translate
        tonChan.setWindowTitle(_translate("tonChan", "tonChan"))
        self.botonIniciar.setText(_translate("tonChan", "Iniciar"))
        self.labelReferencia.setText(_translate("tonChan", "Longitud lado inferior (cm)"))
        self.checkGuardarVideo.setText(_translate("tonChan", "Guardar archivo de video"))
        self.checkDetectarDos.setText(_translate("tonChan", "Detectar dos objetos"))
        self.botonAplicar.setText(_translate("tonChan", "Aplicar"))
        self.menuArchivo.setTitle(_translate("tonChan", "Archivo"))
        self.menuAyuda.setTitle(_translate("tonChan", "Ayuda"))
        self.menuConfiguracion.setTitle(_translate("tonChan", "Configuracion"))
        self.menuColor_Objeto_1.setTitle(_translate("tonChan", "Color Objeto 1"))
        self.menuColor_Objeto_2.setTitle(_translate("tonChan", "Color Objeto 2"))
        self.menuColor_Calibracion.setTitle(_translate("tonChan", "Color Calibracion"))
        self.menuCamara.setTitle(_translate("tonChan", "Camara"))
        self.actionManual.setText(_translate("tonChan", "Manual"))
        self.actionAcercaDe.setText(_translate("tonChan", "Acerca de"))
        self.actionCargarVideo.setText(_translate("tonChan", "Cargar archivo de video"))
        self.actionSalir.setText(_translate("tonChan", "Salir"))
