# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_ui_hi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutWindow(object):
    def setupUi(self, AboutWindow):
        AboutWindow.setObjectName("AboutWindow")
        AboutWindow.resize(450, 268)
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../asst/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutWindow.setWindowIcon(icon)
        
        self.centralwidget = QtWidgets.QWidget(AboutWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 90, 420, 40))
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(10, 120, 420, 40))
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(10, 180, 420, 40))
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(10, 210, 420, 40))
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(10, 150, 420, 40))
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")

        self.gfa_dibujo = QtWidgets.QLabel(self.centralwidget)
        self.gfa_dibujo.setGeometry(QtCore.QRect(55, 10, 340, 80))
        self.gfa_dibujo.setObjectName("gfa_dibujo")
        banner = QtGui.QPixmap("../asst/banner.jpg")
        self.gfa_dibujo.setPixmap(banner)
        self.gfa_dibujo.setScaledContents(True)
        
        AboutWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AboutWindow)
        self.statusbar.setObjectName("statusbar")
        AboutWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AboutWindow)
        QtCore.QMetaObject.connectSlotsByName(AboutWindow)

    def retranslateUi(self, AboutWindow):
        _translate = QtCore.QCoreApplication.translate
        AboutWindow.setWindowTitle(_translate("AboutWindow", "Acerca de"))
        self.label1.setText(_translate("AboutWindow", "Este Software fue desarrollado por"))
        self.label2.setText(_translate("AboutWindow", "Imanol Nuñez Olmos y Gonzalo Lattanzio, y por el"))
        self.label4.setText(_translate("AboutWindow", "de la UTN Facultad Regional Delta (FRD)"))
        self.label5.setText(_translate("AboutWindow", "San Martin 1171, Campana, Bs As, Argentina"))
        self.label3.setText(_translate("AboutWindow", "Grupo de Fotonica Aplicada (GFA)"))
